name: manual
on:
    workflow_dispatch:
        inputs:
            greeting:
                type: string
                defalt: Hello
                required: true
                decscription: A cheerful word
jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - run: echo "${{ inputs.greeting }}"